### ISSUE TITLE
Expand Development Workflow

### ISSUE THREAD

**Issue by cyschneck** [NCAR/geocat-applications#50]
### Expand Development Workflow Overview
Expand the documentation as a part of "For Developers > Contributor's Guide" to cover development workflow in greater depth (similar to depth in [geocat-comp](https://geocat-comp.readthedocs.io/en/stable/contrib.html#development-workflow-overview) and [uxarray](https://uxarray.readthedocs.io/en/latest/contributing.html))

Would be useful to make the instructions for different operating systems

For example, the command `open` does not function in Linux to open the index.html page as it does on Mac
```
If the `_build` folder is generated, but `open` command cannot open the html, you can navigate to the `index.html` document and right-click to `Open With` your desired browser.
```

Contributor's Guide
- Overview of Git and Github
- Conda environment description ([similar to xarray](https://github.com/NCAR/geocat-applications/pull/40#discussion_r1628126372))
- Set up on local machine (fork, clone, etc..)
-  Set up branch and pre-commit hooks
- Choosing between application template options
    - Specify which files should be updated as a part of each template type
    - Address how to contribute to the [csv template](https://github.com/NCAR/geocat-applications/pull/40#discussion_r1628134680)
- Opening PR and addressing feedback

**Comment by anissa111** [comment]
We should expand this issue to cover more than just the `open` command part. I'm not sure the bug template is necessarily the best fit for the intended scope, if that makes sense. Yes, there is technically a "bug", but it's a one or two line change in the broader scope of this ticket, which should talk about, for example, how we want to expand the section, what subsections we should have, how this section might need to be different than the version we have in geocat-comp, ect.

**Comment by cyschneck** [comment]
Agreed, something similar to how geocat-comp is set up:

- Set up on local machine (fork, clone, etc..)
- Set up branch and pre-commit hooks
- Choosing between template options
- Opening PR and feedback
