### ISSUE TITLE
[GA-1527] Proposed structure clarification (pulled from #44)

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-applications#54]
> What about a structure like this?  With the "applications" bit implied.  Side note - at this point I think we're pulling from something a bit broader than just the index of "NCL Applications" scripts anyway so maybe not being so closely tied to that is fine and perhaps less confusing for those w/out the pleasure of having known NCL 🙃 . 
> 
> Python
>  - Visualization 
>     - Plot Types
>  - Analysis
>     - Dates and Times (or maybe we have another view or categorization structure?  probably a later issue
> 
> NCL to Python
>  - Functions, Function Index, or NCL Index (one of these)
>  - Categories or By Category (or similar adjustments to above)
> 
> This might also be something that we have better ideas about in the future.  We can put a pin in it too.

_Originally posted by @kafitzgerald in https://github.com/NCAR/geocat-applications/pull/44#discussion_r1628357263_

**Comment by cyschneck** [comment]
NCL splits up its functions by some handy categories as well:

- Visualization (plots)
- Earth Science (climatology, heat index, lat/lon functions, etc..)
- Math and Statistics (general math, random numbers, etc...)
- General NCL routines (working with arrays, lists, strings, etc..)

Maybe categories like:
- General Functions
- Date and Time
- Visualization
- Earth Science
- Math and Statistics
