### ISSUE TITLE
Type Converters and NCL Receipt

### ISSUE THREAD

**Issue by cyschneck** [NCAR/geocat-applications#64]
### Describe the addition you would like to see.

[Type Converters](https://www.ncl.ucar.edu/Document/Functions/type_convert.shtml)

Initial: Byte
- byte2flt
- byte2flt_hdf

Initial: Float
- floattobyte
- floattochar
- floattocharacter
- floattoint
- floattointeger
- floattoolong
- floattoshort
- flt2dble
- flt2string

Initial: Integer
- int2dble
- int2flt
- integertobyte
- integertochar
- integertocharacter
- integertoshort
- inttobyte
- inttochar
- inttoshort

Initial: Long
- longtobyte
- longtochar
- longtocharacter
- longtoint
- longtointeger
- longtoshort

Initial: String
- cshstringtolist
- stringtochar
- stringtocharacter
- stringtodouble
- stringtofloat
- stringtoint
- stringtointeger
- stringtolong
- stringtoshort

Initial: Double
- dble2flt

Initial: Short
- short2flt
- short2flt_hdf
- shorttobyte
- shorttochar
- shorttocharacter
- ushorttoint

Initial: Numeric
- numeric2int
- tobyte
- tochar
- todouble
- tofloat
- toint
- toint64
- tointeger
- tolong
- toshort
- tosigned
- tostring
- tostring_with_format
- totype
- toubyte
- touint64
- toulong
- tounsigned
- toushort

Other
- datatondc
- ndctodata
- NhlDataToNDC
- NhlNDCToData
- pack_values

### Is this a request for something that previously existed in NCL?

Yes

### Additional context

Many of the functions are duplicates

**Comment by anissa111** [comment]
I'm going to close as part of our project management change over given that this is not priority or active work
