### ISSUE TITLE
Codespell should ignore image data

### ISSUE THREAD

**Issue by andy-theia** [NCAR/geocat-applications#72]
Suggesting we configure codespell to ignore image data

**Comment by kafitzgerald** [comment]
Example here: https://results.pre-commit.ci/run/github/677032883/1719933484.CFPsQ4GEQ5COnsapb8xMrw

**Comment by cyschneck** [comment]
Is the image data from a URL, generated, or stored locally?

**Comment by kafitzgerald** [comment]
> Is the image data from a URL, generated, or stored locally?

It's an output image that's generated by code in the notebook.  

We probably haven't run into this elsewhere because we generally clear the notebooks before committing them to the repo.  This was part of what prompted that Zulip thread earlier today.

**Comment by anissa111** [comment]
Wait, we're not clearing the notebooks before committing them to the repo yet, though.

**Comment by kafitzgerald** [comment]
Yeah, I meant elsewhere on GeoCAT projects.  That was unclear though.

**Comment by cyschneck** [comment]
Might be useful to enable codespell to be [optional warning](https://stackoverflow.com/questions/59730765/is-it-possible-to-run-mypy-pre-commit-without-making-it-fail), but not prevent committing
```
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
    -   id: mypy
        verbose: true
        entry: bash -c 'mypy "$@" || true' --
```
