### ISSUE TITLE
Random Number Generators

### ISSUE THREAD

**Issue by cyschneck** [NCAR/geocat-applications#75]
[NCL Random Number Generators](https://www.ncl.ucar.edu/Document/Functions/random.shtml)

- [generate_2d_array](https://www.ncl.ucar.edu/Document/Functions/Built-in/generate_2d_array.shtml)
- [generate_sample_indices](https://www.ncl.ucar.edu/Document/Functions/Contributed/generate_sample_indices.shtml)
- [generate_unique_indices](https://www.ncl.ucar.edu/Document/Functions/Contributed/generate_unique_indices.shtml)
- [rand](https://www.ncl.ucar.edu/Document/Functions/Built-in/rand.shtml)
- [random_chi](https://www.ncl.ucar.edu/Document/Functions/Built-in/random_chi.shtml)
- [random_gamma](https://www.ncl.ucar.edu/Document/Functions/Built-in/random_gamma.shtml)
- [random_normal](https://www.ncl.ucar.edu/Document/Functions/Built-in/random_normal.shtml)
- [random_setallseed](https://www.ncl.ucar.edu/Document/Functions/Built-in/random_setallseed.shtml)
- [random_uniform](https://www.ncl.ucar.edu/Document/Functions/Built-in/random_uniform.shtml)
- [srand](https://www.ncl.ucar.edu/Document/Functions/Built-in/srand.shtml)

**Comment by anissa111** [comment]
Closing here for now
