### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by jukent** [NCAR/geocat-applications#9]
[NCAR brand standards](https://news.ucar.edu/sites/default/files/documents/related-links/2020-03/NCAR-UCAR_BrandStandards_031020-Spreads.pdf)

We want a consistent top navbar across repositories, a footer that is pinned below the left navbar (doesn't float up if too little content), it to look good on multiple screen sizes and light/dark mode, to make a gallery extension that can be used for each category landing page.

**Comment by anissa111** [comment]
Closing for now in favor of creating more specific issues when appropriate
