### ISSUE TITLE
Update linking to "Pivot to Python"

### ISSUE THREAD

**Issue by cyschneck** [NCAR/geocat-applications#98]
`GETTING_STARTING.md` previously referenced the Pivot to Python initiative, but would be useful to use a less dated page (https://github.com/NCAR/geocat-applications/pull/96)

```
This is part of the GeoCAT's commitment to NCL and NSF NCAR's [Pivot to Python Initiative](https://www.ncl.ucar.edu/Document/Pivot_to_Python/)
```

- Update connected resources and pages for `GETTING_STARTED.md` and `README.md`

**Comment by anissa111** [comment]
While I agree that page is dated, I'm actually not sure that a more up-to-date page exists that is sufficiently detailed like the one we're already linking to.

The point could be made that somebody should update the page, but that's above the scope of this project.

I would be super excited to be wrong about the existence of a suitible page, let me know if there was one you had in mind.

**Comment by cyschneck** [comment]
This came out as the result of [a conversation](https://github.com/NCAR/geocat-applications/pull/96#discussion_r1723808758) from the Getting Started page. I wasn't able to find another page that is more detailed/up-to-date than [this](https://www.ncl.ucar.edu/Document/Pivot_to_Python/), but might be worth bringing up in a weekly meeting

If there is interest in making a new page, I could handle it. it could live on back page of `geocat-applications`, where I imagine it would mostly be duplicate information from the existing page with a few sections to expand out and link users to relevant resources (application index, geocat-comp, geocat-viz, Pythia notebooks). It would also have the advantage of living in a place where it is more clear how that initiative is being developed

**Comment by anissa111** [comment]
Ah, I see, thanks for the context. My reading of @kafitzgerald's comment is more that we should be careful with / consult Orhan on the wording regarding "GeoCAT's commitment to NCL and NSF NCAR's Pivot to Python Initiative" rather than updating the linked content.

Updating the official pivot to python pages or creating pages (here on applications or elsewhere) that are updates to pivot to python should be decisions and content that are made by folks responsible for initiative/strategic messaging.

**Comment by kafitzgerald** [comment]
Sorry for the delay here - still catching up after being out.  

My recollection (similar to Cora's) is that this was logged as a placeholder from a review discussion.  

I think where we landed after the review on that PR is probably fine for now, but it might still be good to update after the GeoCAT website refresh and/or once I get to some updates on the NCL/PyNIO/PyNGL sites.

Either leaving this open as a currently blocked placeholder or closing it out for now works for me.

**Comment by anissa111** [comment]
Okay cool. I'm going to go ahead and close this here for now as I think it'll make more sense to include this task as part of, like, a "update comp and applications docs" after other websites are refreshed.
